A tensor in PyTorch is a multi-dimensional array similar to NumPy arrays but with additional capabilities. Tensors are a fundamental data structure in PyTorch and are used to encode the inputs and outputs of a model, as well as the model's parameters. PyTorch tensors support automatic differentiation, which is essential for training deep learning models.

### Key Features of PyTorch Tensors

1. **Multi-dimensional Array**: Tensors can be 1-dimensional (vectors), 2-dimensional (matrices), or higher-dimensional arrays.
2. **GPU Acceleration**: Tensors can be moved to and operated on a GPU to speed up computation.
3. **Automatic Differentiation**: Tensors can track operations to enable automatic differentiation via PyTorch's autograd system, which is crucial for training neural networks.

### Creating Tensors

You can create tensors in several ways, such as from data, from NumPy arrays, or using built-in functions. Here are some examples:

In [2]:
import torch

# From data
data = [[1, 2], [3, 4]]
tensor_from_data = torch.tensor(data)
print(tensor_from_data)

# From NumPy array
import numpy as np
np_array = np.array(data)
tensor_from_np = torch.from_numpy(np_array)
print(tensor_from_np)

# Using built-in functions
tensor_zeros = torch.zeros(2, 3)   # 2x3 matrix of zeros
tensor_ones = torch.ones(2, 3)     # 2x3 matrix of ones
tensor_random = torch.rand(2, 3)   # 2x3 matrix with random values
print(tensor_zeros)
print(tensor_ones)
print(tensor_random)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.1148, 0.3096, 0.6898],
        [0.7177, 0.3627, 0.7386]])


### Tensor Operations

You can perform a variety of operations on tensors, including arithmetic operations, indexing, slicing, and more:

In [3]:
# Arithmetic operations
tensor_a = torch.tensor([1.0, 2.0, 3.0])
tensor_b = torch.tensor([4.0, 5.0, 6.0])

# Element-wise addition
tensor_sum = tensor_a + tensor_b
print(tensor_sum)

# Element-wise multiplication
tensor_mul = tensor_a * tensor_b
print(tensor_mul)

# Matrix multiplication
tensor_c = torch.tensor([[1, 2], [3, 4]])
tensor_d = torch.tensor([[5, 6], [7, 8]])
tensor_matmul = torch.matmul(tensor_c, tensor_d)
print(tensor_matmul)

# Indexing and slicing
tensor_e = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor_e[0, 0])   # Accessing the first element
print(tensor_e[:, 1])   # Accessing the second column
print(tensor_e[1, :])   # Accessing the second row

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([[19, 22],
        [43, 50]])
tensor(1)
tensor([2, 5, 8])
tensor([4, 5, 6])


### Moving Tensors to GPU

If you have a GPU available, you can move tensors to the GPU to accelerate computation:


In [4]:
# Check if GPU is available
if torch.cuda.is_available():
    tensor_gpu = tensor_a.to('cuda')
    print(tensor_gpu)

### Automatic Differentiation

Tensors with the attribute `requires_grad=True` will track operations on them. When you call `.backward()`, the gradient of these tensors will be calculated and stored in the `.grad` attribute.


In [5]:
# Creating a tensor with requires_grad=True
tensor_f = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# Perform some operations
result = tensor_f * 2 # each element multiply by 2 which is the gradient
result_sum = result.sum()

# Compute gradients
result_sum.backward()

# Display gradients
print(tensor_f.grad)

tensor([2., 2., 2.])


👍😄 **Conclusion**: In summary, PyTorch tensors are versatile, support GPU acceleration, and are fundamental for building and training neural networks due to their ability to track gradients.